// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVrA1aLeC-aynnmZidrR479PgRDBjLXI8',
    appId: '1:276887789667:android:baa23e4c655c8411261856',
    messagingSenderId: '276887789667',
    projectId: 'programmers-ke',
    storageBucket: 'programmers-ke.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6X9BC9X9xjMdJ6IiTuiZnPnJciufq1qU',
    appId: '1:276887789667:ios:4c6518f12d646b28261856',
    messagingSenderId: '276887789667',
    projectId: 'programmers-ke',
    storageBucket: 'programmers-ke.appspot.com',
    iosClientId: '276887789667-hdtv2redcbv5b8vr4q87p22lv0pq20od.apps.googleusercontent.com',
    iosBundleId: 'com.example.programmersKeFlutter',
  );
}
